---
apiVersion: v1
data:
  NEWRELIC_PHP_ENABLED:       "1"
  NEWRELIC_PHP_APPNAME:       "Example App"
  NEWRELIC_PHP_LOGFILE:       "/proc/self/fd/2"
  NEWRELIC_PHP_LOGLEVEL:      "debug"
  NEWRELIC_DAEMON_HOST:       "newrelic-daemon.default.svc.cluster.local"
  NEWRELIC_DAEMON_PORT:       "33142"
  NEWRELIC_DAEMON_SOCAT_PORT: "33143"
  NEWRELIC_PHP_LICENSE:       "$NEWRELIC_PHP_LICENSE"
kind: ConfigMap
metadata:
  name: newrelic-env-config
